In [1]:
import numpy as np

**Example (functions)**

In [2]:
def f(x):
    return 2*x

In [3]:
f(3)

6

**Example (vectors)**

In [6]:
# operation "+" on built-in and numpy vectors
x = [1,2,3]
y = [-1, 1, -1]
x+y
type(x)

x = np.array([1,2,3])
y = np.array([-1,1,-1])
x+y

array([0, 3, 2])

**Example (dataframes)**

In [7]:
import pandas as pd

In [9]:
# specify rows
row_1 = [1, 0.5]
row_2 = [3, 0.25]

table = pd.DataFrame(data = [row_1, row_2], columns = ["Mean", "Stdev"])
table

   Mean  Stdev
0     1   0.50
1     3   0.25

In [11]:
# specify columns
d = {'Mean': [1, 3], 'Stdev': [0.5, 0.25]}
table = pd.DataFrame(data=d)
table

   Mean  Stdev
0     1   0.50
1     3   0.25

In [19]:
google_data = pd.read_csv('Topic 1 (Basics)_data.csv')
google_data
# type(google_data)

,symbol,date,open,high,low,close,volume,adjclose,dividends,splits
0,GOOG,2004-08-19,2.490664,2.591785,2.390042,2.499133,897427216,2.482147,0.0,0.0
1,GOOG,2004-08-20,2.515820,2.716817,2.503118,2.697639,458857488,2.679304,0.0,0.0
2,GOOG,2004-08-23,2.758411,2.826406,2.716070,2.724787,366857939,2.706268,0.0,0.0
3,GOOG,2004-08-24,2.770615,2.779581,2.579581,2.611960,306396159,2.594207,0.0,0.0
4,GOOG,2004-08-25,2.614201,2.689918,2.587302,2.640104,184645512,2.622160,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
5322,GOOG,2025-10-14,241.755005,248.024994,241.177994,246.190002,17705400,246.190002,0.0,0.0
5323,GOOG,2025-10-15,248.085007,252.759995,246.789993,251.710007,16048100,251.710007,0.0,0.0
5324,GOOG,2025-10-16,252.464996,257.579987,250.669998,251.880005,18946000,251.880005,0.0,0.0
5325,GOOG,2025-10-17,251.350006,254.880005,248.589996,253.789993,17586000,253.789993,0.0,0.0
5326,GOOG,2025-10-20 15:30:16-04:00,255.160004,257.869995,254.600006,256.899994,8695588,256.899994,0.0,0.0

In [24]:
# access by column
google_data['close']
# access by row
google_data.iloc[1]

symbol             GOOG
date         2004-08-20
open            2.51582
high           2.716817
low            2.503118
close          2.697639
volume        458857488
adjclose       2.679304
dividends           0.0
splits              0.0
Name: 1, dtype: object

Dynamic data upload

In [12]:
from yahooquery import Ticker

pip install yahooquery

https://yahooquery.dpguthrie.com/<br>
https://yahooquery.dpguthrie.com/guide/ticker/historical/

In [25]:
snp = Ticker('^GSPC')
snp_data = snp.history(start='2009-01-01', interval = '1d')
snp_data
# snp_data.columns
# snp_data.index

                          open         high          low        close  \
symbol date
^GSPC  2009-01-02   902.989990   934.729980   899.349976   931.799988
       2009-01-05   929.169983   936.630005   919.530029   927.450012
       2009-01-06   931.169983   943.849976   927.280029   934.700012
       2009-01-07   927.450012   927.450012   902.369995   906.650024
       2009-01-08   905.729980   910.000000   896.809998   909.729980
...                        ...          ...          ...          ...
       2026-01-14  6937.410156  6941.299805  6885.740234  6926.600098
       2026-01-15  6969.459961  6979.339844  6937.930176  6944.470215
       2026-01-16  6960.540039  6967.299805  6925.089844  6940.009766
       2026-01-20  6865.240234  6871.169922  6789.049805  6796.859863
       2026-01-21  6810.709961  6910.390137  6804.959961  6875.620117

                       volume     adjclose
symbol date
^GSPC  2009-01-02  4048270000   931.799988
       2009-01-05  5413910000   927.450012
       2009-01-06  5392620000   934.700012
       2009-01-07  4704940000   906.650024
       2009-01-08  4991550000   909.729980
...                       ...          ...
       2026-01-14  5530830000  6926.600098
       2026-01-15  5114050000  6944.470215
       2026-01-16  5356550000  6940.009766
       2026-01-20  5769500000  6796.859863
       2026-01-21  5835520000  6875.620117

[4289 rows x 6 columns]

In [31]:
snp_data.index
# get data

prices = snp_data['close']
dates = snp_data.index.get_level_values(1)

In [33]:
import plotly.graph_objects as go

**Example (Graphs)**

In [36]:
# Scatterplot
graph = go.Figure()

scatter = go.Scatter(x = dates, y = prices)
graph.add_trace(scatter)

graph.show()

In [46]:
# Histogram
graph = go.Figure()
hist = go.Histogram(x = prices, histnorm = 'probability density', nbinsx = 60)
graph.add_trace(hist)
graph.show()